apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 1337
